

export const episode = {
    "audio_preview_url": "https://p.scdn.co/mp3-preview/566fcc94708f39bcddc09e4ce84a8e5db8f07d4d",
    "description": "En ny tysk bok granskar för första gången Tredje rikets drogberoende, från Führerns knarkande till hans soldater på speed. Och kändisförfattaren Antony Beevor får nu kritik av en svensk kollega.  Hitler var beroende av sin livläkare, som gav honom mängder av narkotiska preparat, och blitzkrigssoldaterna knaprade 35 miljoner speedtabletter under invasionen av Frankrike 1940. I den nyutkomna boken Der Totale Rausch, Det totala ruset, ger författaren Norman Ohler för första gången en samlad bild av knarkandet i Tredje riket. Mycket tyder på att Hitler var gravt drogpåverkad under flera avgörande beslut under kriget, säger han, och får medhåll av medicinhistorikern Peter Steinkamp som undersökt de tyska soldaternas intensiva användande av pervitin, en variant av crystal meth.Dessutom får nu den kände militärhistoriska författaren Antony Beevor kritik för att hans senaste bok om Ardenneroffensiven lutar sig alltför tungt mot amerikanska källor, och dessutom innehåller många felaktiga detaljer. Det menar författarkollegan Christer Bergström, som själv skrivit en bok om striderna i Ardennerna.Programledare är Tobias Svanelid.",
    "duration_ms": 1502795,
    "explicit": false,
    "external_urls": {
      "spotify": "https://open.spotify.com/episode/512ojhOuo1ktJprKbVcKyQ"
    },
    "href": "https://api.spotify.com/v1/episodes/512ojhOuo1ktJprKbVcKyQ",
    "html_description": "En ny tysk bok granskar för första gången Tredje rikets drogberoende, från Führerns knarkande till hans soldater på speed. Och kändisförfattaren Antony Beevor får nu kritik av en svensk kollega. <br /><br /> Hitler var beroende av sin livläkare, som gav honom mängder av narkotiska preparat, och blitzkrigssoldaterna knaprade 35 miljoner speedtabletter under invasionen av Frankrike 1940. I den nyutkomna boken Der Totale Rausch, Det totala ruset, ger författaren Norman Ohler för första gången en samlad bild av knarkandet i Tredje riket. Mycket tyder på att Hitler var gravt drogpåverkad under flera avgörande beslut under kriget, säger han, och får medhåll av medicinhistorikern Peter Steinkamp som undersökt de tyska soldaternas intensiva användande av pervitin, en variant av crystal meth.Dessutom får nu den kände militärhistoriska författaren Antony Beevor kritik för att hans senaste bok om Ardenneroffensiven lutar sig alltför tungt mot amerikanska källor, och dessutom innehåller många felaktiga detaljer. Det menar författarkollegan Christer Bergström, som själv skrivit en bok om striderna i Ardennerna.Programledare är Tobias Svanelid.",
    "id": "512ojhOuo1ktJprKbVcKyQ",
    "images": [
      {
        "height": 640,
        "url": "https://i.scdn.co/image/de4a5f115ac6f6ca4cae4fb7aaf27bacac7a0b8a",
        "width": 640
      },
      {
        "height": 300,
        "url": "https://i.scdn.co/image/fb8dcbdb0cbf8db2a669e9caaf41b23b1a9b5d83",
        "width": 300
      },
      {
        "height": 64,
        "url": "https://i.scdn.co/image/bb0a73654387988ef636a31a8ac312f01c74f36a",
        "width": 64
      }
    ],
    "is_externally_hosted": false,
    "is_playable": true,
    "language": "sv",
    "languages": [
      "sv"
    ],
    "name": "Tredje rikets knarkande granskas",
    "release_date": "2015-10-01",
    "release_date_precision": "day",
    "show": {
      "available_markets": [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BZ",
        "CA",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KH",
        "KI",
        "KM",
        "KN",
        "KW",
        "LA",
        "LB",
        "LC",
        "LI",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "US",
        "UY",
        "UZ",
        "VC",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW"
      ],
      "copyrights": [],
      "description": "Vi är där historien är. Ansvarig utgivare: Nina Glans",
      "explicit": false,
      "external_urls": {
        "spotify": "https://open.spotify.com/show/38bS44xjbVVZ3No3ByF1dJ"
      },
      "href": "https://api.spotify.com/v1/shows/38bS44xjbVVZ3No3ByF1dJ",
      "html_description": "Vi är där historien är.<br/>Ansvarig utgivare: Nina Glans",
      "id": "38bS44xjbVVZ3No3ByF1dJ",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/84bc7407c7a61e805284314bef8b9ed5a7c31426",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/4b89f866aa625cf02f98f80b968da52b65944bf2",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/cc1e47c7e3e5a169d2352e81dc1a681ac7bbc0bd",
          "width": 64
        }
      ],
      "is_externally_hosted": false,
      "languages": [
        "sv"
      ],
      "media_type": "audio",
      "name": "Vetenskapsradion Historia",
      "publisher": "Sveriges Radio",
      "total_episodes": 500,
      "type": "show",
      "uri": "spotify:show:38bS44xjbVVZ3No3ByF1dJ"
    },
    "type": "episode",
    "uri": "spotify:episode:512ojhOuo1ktJprKbVcKyQ"
  }