export const HMTimerTrigger = {
  "name": "",
  "isEnabled": "",
  "lastFireDate": "",
  "uniqueIdentifier": "",
  "actionSets": [{
    "uniqueIdentifier": "d0f88116-fa1e-4842-8a70-d031151cea62",
    "name": "Action Set 1",
    "actionSetType": "HMActionSetTypeHomeArrival",
    "actions": [{
        "uniqueIdentifier": "c448faee-b7df-4332-9ccb-1444599a3506"
    }],
    "isExecuting": false,
    "lastExecutionDate": 1659367125,
  }],
  "fireDate": {
      "identifier": "",
      "nextDaylightSavingTimeTransition": "",
      "description": "",
      "debugDescription": "",
      "customMirror": "",
      "hashValue": 0
  },
  "recurrence": {
      "calender": null,
      "timeZone": null,
      "isValidDate": false,
      "date": null,
      "era": null,
      "year": null,
      "yearForWeekOfYear": null,
      "quarter": null,
      "month": null,
      "isLeapMonth": null,
      "weekOfMonth": null,
      "weekOfYear": null,
      "weekday": null,
      "weekdayOrdinal": null,
      "day": null,
      "hour": null,
      "minute": null,
      "second": null,
      "nanosecond": null,
      "description": "",
      "debugDescription": "",
      "customMirror": "",
      "hashValue": 0
  },
  "recurrenceCalendar": {
      "identifier": "",
      "locale": "",
      "firstWeekday": "",
      "minimumDaysInFirstWeek": "",
      "timeZone": "",
      "weekday": "",
      "amSybmbol": "",
      "pmSybmbol": "",
      "weekdaySymbols": [""],
      "shortWeekdaySymbols": [""],
      "veryShortWeekdaySymbols": [""],
      "standaloneWeekdaySymbols": [""],
      "shortStandaloneWeekdaySymbols": [""],
      "veryStandaloneWeekdaySymbols": [""],
      "monthSymbols": [""],
      "shortMonthSymbols": [""],
      "veryShortMonthSymbols": [""],
      "standaloneMonthSymbols": [""],
      "shortStandaloneMonthSymbols": [""],
      "veryShortStandaloneMonthSymbols": [""],
      "quarterSymbols": [""],
      "shortQuarterSymbols": [""],
      "standaloneQuarterSymbols": [""],
      "shortStandaloneQuarterSymbols": "",
      "eraSymbols": "",
      "longEraSymbols": [""],
      "description": "",
      "debugDescription": "",
      "customMirror": {},
      "hashValue": 0
  },
  "timeZone": {
      "identifier": "",
      "nextDaylightSavingTimeTransition": "",
      "description": "",
      "debugDescription": "",
      "customMirror": "",
      "hashValue": 0
  }
}